name = "3dprinter-web-api"
main = "src/index.ts"
compatibility_date = "2024-10-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "COLOR_CACHE"
id = "546aedc37b4843489e0f8c4a1f3799f5"
preview_id = "afc12a8d74f44a4495eb108777501e06"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "uploads"
preview_bucket_name = "preview-uploads"

[[d1_databases]]
binding = "DB"
database_name = "ecommerce"
database_id = "ec1d6de0-2452-4506-8108-0aed31575e60"
migrations_dir = "./drizzle/migrations"
preview_database_id = "local-ecommerce-db"

[env.production.vars]
DOMAIN = "https://rc-store.benhalverson.dev"
RP_ID = "rc-store.benhalverson.dev"
