name = "3dprinter-web-api"
main = "src/index.ts"
compatibility_date = "2024-10-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "COLOR_CACHE"
id = "546aedc37b4843489e0f8c4a1f3799f5"
preview_id = "afc12a8d74f44a4495eb108777501e06"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "uploads"
preview_bucket_name = "preview-uploads"

[[r2_buckets]]
binding = "PHOTO_BUCKET"
bucket_name = "photos"
preview_bucket_name = "preview-photos"

[[d1_databases]]
binding = "DB"
database_name = "ecommerce"
database_id = "8ea08f02-696c-4410-a690-2bf1fa0333dc"
migrations_dir = "./drizzle/migrations"

[[d1_databases]]
binding = "DB_PREVIEW"
database_name = "ecommerce-preview"
database_id= "b72c9b13-20c3-49e7-b5df-e46ee646d82b"
migrations_dir = "./drizzle/migrations"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "81516966d6ad4902bf63e82b284c0617"
preview_id = "c7d43c86ba9c4f5c9419970c12bb2fca"

[vars]
DOMAIN = "https://rc-store.benhalverson.dev"
RP_ID = "rc-store.benhalverson.dev"
PASSKEY_ORIGIN = "https://rc-store.benhalverson.dev"
R2_PUBLIC_BASE_URL = "https://uploads.benhalverson.dev"
R2_PHOTO_BASE_URL = "https://photos.benhalverson.dev"
